package br.edu.ifpb.enums;

public enum ReserveMenuOption {
    ADD_RESERVE_OPTION,
    LIST_RESERVES_OPTION,
    EDIT_RESERVE_OPTION,
    CHECK_OUT_RESERVE_OPTION,
    REMOVE_RESERVE_OPTION,
    LIST_ROOMS_OPTION,
    LIST_AVAILABLE_ROOMS_OPTION,
    RETURN_OPTION
}
